/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutConciergeCareRouteImport } from './routes/about-concierge-care'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AffiliateBenefitsRouteImport } from './routes/affiliate-benefits'
import { Route as BecomeAnAffiliateRouteImport } from './routes/become-an-affiliate'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DoNotSellRouteImport } from './routes/do-not-sell'
import { Route as FindADoctorRouteImport } from './routes/find-a-doctor'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MemberBenefitsRouteImport } from './routes/member-benefits'
import { Route as MemberFaqRouteImport } from './routes/member-faq'
import { Route as MemberProgramsRouteImport } from './routes/member-programs'
import { Route as NonDiscriminationRouteImport } from './routes/non-discrimination'
import { Route as OurDoctorsRouteImport } from './routes/our-doctors'
import { Route as OurMissionRouteImport } from './routes/our-mission'
import { Route as OurTeamRouteImport } from './routes/our-team'
import { Route as PhysicianFaqRouteImport } from './routes/physician-faq'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SellYourPracticeRouteImport } from './routes/sell-your-practice'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SuccessStoriesRouteImport } from './routes/success-stories'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as TransitionRouteImport } from './routes/transition'
import { Route as VideoLibraryRouteImport } from './routes/video-library'
import { Route as WhatIsConciergeMedicineRouteImport } from './routes/what-is-concierge-medicine'
import { Route as WhyConciergeMedicineRouteImport } from './routes/why-concierge-medicine'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminCareRouteImport } from './routes/admin.care'
import { Route as AdminDoctorsRouteImport } from './routes/admin.doctors'
import { Route as AdminFaqsRouteImport } from './routes/admin.faqs'
import { Route as AdminInboxRouteImport } from './routes/admin.inbox'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminPerksRouteImport } from './routes/admin.perks'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminStepsRouteImport } from './routes/admin.steps'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminVideosRouteImport } from './routes/admin.videos'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as DoctorsSlugRouteImport } from './routes/doctors.$slug'
import { Route as ForDoctorsBlogRouteImport } from './routes/for-doctors.blog'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutConciergeCareRoute = AboutConciergeCareRouteImport.update({
  id: '/about-concierge-care',
  path: '/about-concierge-care',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AffiliateBenefitsRoute = AffiliateBenefitsRouteImport.update({
  id: '/affiliate-benefits',
  path: '/affiliate-benefits',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeAnAffiliateRoute = BecomeAnAffiliateRouteImport.update({
  id: '/become-an-affiliate',
  path: '/become-an-affiliate',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DoNotSellRoute = DoNotSellRouteImport.update({
  id: '/do-not-sell',
  path: '/do-not-sell',
  getParentRoute: () => rootRouteImport,
} as any)
const FindADoctorRoute = FindADoctorRouteImport.update({
  id: '/find-a-doctor',
  path: '/find-a-doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberBenefitsRoute = MemberBenefitsRouteImport.update({
  id: '/member-benefits',
  path: '/member-benefits',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberFaqRoute = MemberFaqRouteImport.update({
  id: '/member-faq',
  path: '/member-faq',
  getParentRoute: () => rootRouteImport,
} as any)
const MemberProgramsRoute = MemberProgramsRouteImport.update({
  id: '/member-programs',
  path: '/member-programs',
  getParentRoute: () => rootRouteImport,
} as any)
const NonDiscriminationRoute = NonDiscriminationRouteImport.update({
  id: '/non-discrimination',
  path: '/non-discrimination',
  getParentRoute: () => rootRouteImport,
} as any)
const OurDoctorsRoute = OurDoctorsRouteImport.update({
  id: '/our-doctors',
  path: '/our-doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const OurMissionRoute = OurMissionRouteImport.update({
  id: '/our-mission',
  path: '/our-mission',
  getParentRoute: () => rootRouteImport,
} as any)
const OurTeamRoute = OurTeamRouteImport.update({
  id: '/our-team',
  path: '/our-team',
  getParentRoute: () => rootRouteImport,
} as any)
const PhysicianFaqRoute = PhysicianFaqRouteImport.update({
  id: '/physician-faq',
  path: '/physician-faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SellYourPracticeRoute = SellYourPracticeRouteImport.update({
  id: '/sell-your-practice',
  path: '/sell-your-practice',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessStoriesRoute = SuccessStoriesRouteImport.update({
  id: '/success-stories',
  path: '/success-stories',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const TransitionRoute = TransitionRouteImport.update({
  id: '/transition',
  path: '/transition',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoLibraryRoute = VideoLibraryRouteImport.update({
  id: '/video-library',
  path: '/video-library',
  getParentRoute: () => rootRouteImport,
} as any)
const WhatIsConciergeMedicineRoute = WhatIsConciergeMedicineRouteImport.update({
  id: '/what-is-concierge-medicine',
  path: '/what-is-concierge-medicine',
  getParentRoute: () => rootRouteImport,
} as any)
const WhyConciergeMedicineRoute = WhyConciergeMedicineRouteImport.update({
  id: '/why-concierge-medicine',
  path: '/why-concierge-medicine',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCareRoute = AdminCareRouteImport.update({
  id: '/care',
  path: '/care',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInboxRoute = AdminInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPerksRoute = AdminPerksRouteImport.update({
  id: '/perks',
  path: '/perks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStepsRoute = AdminStepsRouteImport.update({
  id: '/steps',
  path: '/steps',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVideosRoute = AdminVideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => AdminRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const DoctorsSlugRoute = DoctorsSlugRouteImport.update({
  id: '/doctors/$slug',
  path: '/doctors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ForDoctorsBlogRoute = ForDoctorsBlogRouteImport.update({
  id: '/for-doctors/blog',
  path: '/for-doctors/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about-concierge-care': typeof AboutConciergeCareRoute
  '/admin': typeof AdminRouteWithChildren
  '/affiliate-benefits': typeof AffiliateBenefitsRoute
  '/become-an-affiliate': typeof BecomeAnAffiliateRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/do-not-sell': typeof DoNotSellRoute
  '/find-a-doctor': typeof FindADoctorRoute
  '/login': typeof LoginRoute
  '/member-benefits': typeof MemberBenefitsRoute
  '/member-faq': typeof MemberFaqRoute
  '/member-programs': typeof MemberProgramsRoute
  '/non-discrimination': typeof NonDiscriminationRoute
  '/our-doctors': typeof OurDoctorsRoute
  '/our-mission': typeof OurMissionRoute
  '/our-team': typeof OurTeamRoute
  '/physician-faq': typeof PhysicianFaqRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sell-your-practice': typeof SellYourPracticeRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/transition': typeof TransitionRoute
  '/video-library': typeof VideoLibraryRoute
  '/what-is-concierge-medicine': typeof WhatIsConciergeMedicineRoute
  '/why-concierge-medicine': typeof WhyConciergeMedicineRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/care': typeof AdminCareRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/perks': typeof AdminPerksRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/steps': typeof AdminStepsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/for-doctors/blog': typeof ForDoctorsBlogRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about-concierge-care': typeof AboutConciergeCareRoute
  '/affiliate-benefits': typeof AffiliateBenefitsRoute
  '/become-an-affiliate': typeof BecomeAnAffiliateRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/do-not-sell': typeof DoNotSellRoute
  '/find-a-doctor': typeof FindADoctorRoute
  '/login': typeof LoginRoute
  '/member-benefits': typeof MemberBenefitsRoute
  '/member-faq': typeof MemberFaqRoute
  '/member-programs': typeof MemberProgramsRoute
  '/non-discrimination': typeof NonDiscriminationRoute
  '/our-doctors': typeof OurDoctorsRoute
  '/our-mission': typeof OurMissionRoute
  '/our-team': typeof OurTeamRoute
  '/physician-faq': typeof PhysicianFaqRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sell-your-practice': typeof SellYourPracticeRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/transition': typeof TransitionRoute
  '/video-library': typeof VideoLibraryRoute
  '/what-is-concierge-medicine': typeof WhatIsConciergeMedicineRoute
  '/why-concierge-medicine': typeof WhyConciergeMedicineRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/care': typeof AdminCareRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/perks': typeof AdminPerksRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/steps': typeof AdminStepsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/for-doctors/blog': typeof ForDoctorsBlogRoute
  '/admin': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about-concierge-care': typeof AboutConciergeCareRoute
  '/admin': typeof AdminRouteWithChildren
  '/affiliate-benefits': typeof AffiliateBenefitsRoute
  '/become-an-affiliate': typeof BecomeAnAffiliateRoute
  '/blog': typeof BlogRouteWithChildren
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/do-not-sell': typeof DoNotSellRoute
  '/find-a-doctor': typeof FindADoctorRoute
  '/login': typeof LoginRoute
  '/member-benefits': typeof MemberBenefitsRoute
  '/member-faq': typeof MemberFaqRoute
  '/member-programs': typeof MemberProgramsRoute
  '/non-discrimination': typeof NonDiscriminationRoute
  '/our-doctors': typeof OurDoctorsRoute
  '/our-mission': typeof OurMissionRoute
  '/our-team': typeof OurTeamRoute
  '/physician-faq': typeof PhysicianFaqRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sell-your-practice': typeof SellYourPracticeRoute
  '/sitemap': typeof SitemapRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/success-stories': typeof SuccessStoriesRoute
  '/terms': typeof TermsRoute
  '/testimonials': typeof TestimonialsRoute
  '/transition': typeof TransitionRoute
  '/video-library': typeof VideoLibraryRoute
  '/what-is-concierge-medicine': typeof WhatIsConciergeMedicineRoute
  '/why-concierge-medicine': typeof WhyConciergeMedicineRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/care': typeof AdminCareRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/inbox': typeof AdminInboxRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/perks': typeof AdminPerksRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/steps': typeof AdminStepsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/videos': typeof AdminVideosRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/doctors/$slug': typeof DoctorsSlugRoute
  '/for-doctors/blog': typeof ForDoctorsBlogRoute
  '/admin/': typeof AdminIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about-concierge-care'
    | '/admin'
    | '/affiliate-benefits'
    | '/become-an-affiliate'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/do-not-sell'
    | '/find-a-doctor'
    | '/login'
    | '/member-benefits'
    | '/member-faq'
    | '/member-programs'
    | '/non-discrimination'
    | '/our-doctors'
    | '/our-mission'
    | '/our-team'
    | '/physician-faq'
    | '/privacy'
    | '/reset-password'
    | '/robots.txt'
    | '/sell-your-practice'
    | '/sitemap'
    | '/sitemap.xml'
    | '/success-stories'
    | '/terms'
    | '/testimonials'
    | '/transition'
    | '/video-library'
    | '/what-is-concierge-medicine'
    | '/why-concierge-medicine'
    | '/admin/activity'
    | '/admin/blog'
    | '/admin/care'
    | '/admin/doctors'
    | '/admin/faqs'
    | '/admin/inbox'
    | '/admin/pages'
    | '/admin/perks'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/steps'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/users'
    | '/admin/videos'
    | '/blog/$slug'
    | '/doctors/$slug'
    | '/for-doctors/blog'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about-concierge-care'
    | '/affiliate-benefits'
    | '/become-an-affiliate'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/do-not-sell'
    | '/find-a-doctor'
    | '/login'
    | '/member-benefits'
    | '/member-faq'
    | '/member-programs'
    | '/non-discrimination'
    | '/our-doctors'
    | '/our-mission'
    | '/our-team'
    | '/physician-faq'
    | '/privacy'
    | '/reset-password'
    | '/robots.txt'
    | '/sell-your-practice'
    | '/sitemap'
    | '/sitemap.xml'
    | '/success-stories'
    | '/terms'
    | '/testimonials'
    | '/transition'
    | '/video-library'
    | '/what-is-concierge-medicine'
    | '/why-concierge-medicine'
    | '/admin/activity'
    | '/admin/blog'
    | '/admin/care'
    | '/admin/doctors'
    | '/admin/faqs'
    | '/admin/inbox'
    | '/admin/pages'
    | '/admin/perks'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/steps'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/users'
    | '/admin/videos'
    | '/blog/$slug'
    | '/doctors/$slug'
    | '/for-doctors/blog'
    | '/admin'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about-concierge-care'
    | '/admin'
    | '/affiliate-benefits'
    | '/become-an-affiliate'
    | '/blog'
    | '/careers'
    | '/contact'
    | '/do-not-sell'
    | '/find-a-doctor'
    | '/login'
    | '/member-benefits'
    | '/member-faq'
    | '/member-programs'
    | '/non-discrimination'
    | '/our-doctors'
    | '/our-mission'
    | '/our-team'
    | '/physician-faq'
    | '/privacy'
    | '/reset-password'
    | '/robots.txt'
    | '/sell-your-practice'
    | '/sitemap'
    | '/sitemap.xml'
    | '/success-stories'
    | '/terms'
    | '/testimonials'
    | '/transition'
    | '/video-library'
    | '/what-is-concierge-medicine'
    | '/why-concierge-medicine'
    | '/admin/activity'
    | '/admin/blog'
    | '/admin/care'
    | '/admin/doctors'
    | '/admin/faqs'
    | '/admin/inbox'
    | '/admin/pages'
    | '/admin/perks'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/steps'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/users'
    | '/admin/videos'
    | '/blog/$slug'
    | '/doctors/$slug'
    | '/for-doctors/blog'
    | '/admin/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutConciergeCareRoute: typeof AboutConciergeCareRoute
  AdminRoute: typeof AdminRouteWithChildren
  AffiliateBenefitsRoute: typeof AffiliateBenefitsRoute
  BecomeAnAffiliateRoute: typeof BecomeAnAffiliateRoute
  BlogRoute: typeof BlogRouteWithChildren
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  DoNotSellRoute: typeof DoNotSellRoute
  FindADoctorRoute: typeof FindADoctorRoute
  LoginRoute: typeof LoginRoute
  MemberBenefitsRoute: typeof MemberBenefitsRoute
  MemberFaqRoute: typeof MemberFaqRoute
  MemberProgramsRoute: typeof MemberProgramsRoute
  NonDiscriminationRoute: typeof NonDiscriminationRoute
  OurDoctorsRoute: typeof OurDoctorsRoute
  OurMissionRoute: typeof OurMissionRoute
  OurTeamRoute: typeof OurTeamRoute
  PhysicianFaqRoute: typeof PhysicianFaqRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SellYourPracticeRoute: typeof SellYourPracticeRoute
  SitemapRoute: typeof SitemapRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SuccessStoriesRoute: typeof SuccessStoriesRoute
  TermsRoute: typeof TermsRoute
  TestimonialsRoute: typeof TestimonialsRoute
  TransitionRoute: typeof TransitionRoute
  VideoLibraryRoute: typeof VideoLibraryRoute
  WhatIsConciergeMedicineRoute: typeof WhatIsConciergeMedicineRoute
  WhyConciergeMedicineRoute: typeof WhyConciergeMedicineRoute
  DoctorsSlugRoute: typeof DoctorsSlugRoute
  ForDoctorsBlogRoute: typeof ForDoctorsBlogRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about-concierge-care': {
      id: '/about-concierge-care'
      path: '/about-concierge-care'
      fullPath: '/about-concierge-care'
      preLoaderRoute: typeof AboutConciergeCareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/affiliate-benefits': {
      id: '/affiliate-benefits'
      path: '/affiliate-benefits'
      fullPath: '/affiliate-benefits'
      preLoaderRoute: typeof AffiliateBenefitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-an-affiliate': {
      id: '/become-an-affiliate'
      path: '/become-an-affiliate'
      fullPath: '/become-an-affiliate'
      preLoaderRoute: typeof BecomeAnAffiliateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/do-not-sell': {
      id: '/do-not-sell'
      path: '/do-not-sell'
      fullPath: '/do-not-sell'
      preLoaderRoute: typeof DoNotSellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-a-doctor': {
      id: '/find-a-doctor'
      path: '/find-a-doctor'
      fullPath: '/find-a-doctor'
      preLoaderRoute: typeof FindADoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member-benefits': {
      id: '/member-benefits'
      path: '/member-benefits'
      fullPath: '/member-benefits'
      preLoaderRoute: typeof MemberBenefitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member-faq': {
      id: '/member-faq'
      path: '/member-faq'
      fullPath: '/member-faq'
      preLoaderRoute: typeof MemberFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/member-programs': {
      id: '/member-programs'
      path: '/member-programs'
      fullPath: '/member-programs'
      preLoaderRoute: typeof MemberProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/non-discrimination': {
      id: '/non-discrimination'
      path: '/non-discrimination'
      fullPath: '/non-discrimination'
      preLoaderRoute: typeof NonDiscriminationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-doctors': {
      id: '/our-doctors'
      path: '/our-doctors'
      fullPath: '/our-doctors'
      preLoaderRoute: typeof OurDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-mission': {
      id: '/our-mission'
      path: '/our-mission'
      fullPath: '/our-mission'
      preLoaderRoute: typeof OurMissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/our-team': {
      id: '/our-team'
      path: '/our-team'
      fullPath: '/our-team'
      preLoaderRoute: typeof OurTeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/physician-faq': {
      id: '/physician-faq'
      path: '/physician-faq'
      fullPath: '/physician-faq'
      preLoaderRoute: typeof PhysicianFaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell-your-practice': {
      id: '/sell-your-practice'
      path: '/sell-your-practice'
      fullPath: '/sell-your-practice'
      preLoaderRoute: typeof SellYourPracticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success-stories': {
      id: '/success-stories'
      path: '/success-stories'
      fullPath: '/success-stories'
      preLoaderRoute: typeof SuccessStoriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transition': {
      id: '/transition'
      path: '/transition'
      fullPath: '/transition'
      preLoaderRoute: typeof TransitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video-library': {
      id: '/video-library'
      path: '/video-library'
      fullPath: '/video-library'
      preLoaderRoute: typeof VideoLibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/what-is-concierge-medicine': {
      id: '/what-is-concierge-medicine'
      path: '/what-is-concierge-medicine'
      fullPath: '/what-is-concierge-medicine'
      preLoaderRoute: typeof WhatIsConciergeMedicineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/why-concierge-medicine': {
      id: '/why-concierge-medicine'
      path: '/why-concierge-medicine'
      fullPath: '/why-concierge-medicine'
      preLoaderRoute: typeof WhyConciergeMedicineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/care': {
      id: '/admin/care'
      path: '/care'
      fullPath: '/admin/care'
      preLoaderRoute: typeof AdminCareRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inbox': {
      id: '/admin/inbox'
      path: '/inbox'
      fullPath: '/admin/inbox'
      preLoaderRoute: typeof AdminInboxRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/perks': {
      id: '/admin/perks'
      path: '/perks'
      fullPath: '/admin/perks'
      preLoaderRoute: typeof AdminPerksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/steps': {
      id: '/admin/steps'
      path: '/steps'
      fullPath: '/admin/steps'
      preLoaderRoute: typeof AdminStepsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/videos': {
      id: '/admin/videos'
      path: '/videos'
      fullPath: '/admin/videos'
      preLoaderRoute: typeof AdminVideosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/doctors/$slug': {
      id: '/doctors/$slug'
      path: '/doctors/$slug'
      fullPath: '/doctors/$slug'
      preLoaderRoute: typeof DoctorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-doctors/blog': {
      id: '/for-doctors/blog'
      path: '/for-doctors/blog'
      fullPath: '/for-doctors/blog'
      preLoaderRoute: typeof ForDoctorsBlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCareRoute: typeof AdminCareRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminInboxRoute: typeof AdminInboxRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminPerksRoute: typeof AdminPerksRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminStepsRoute: typeof AdminStepsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminVideosRoute: typeof AdminVideosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminCareRoute: AdminCareRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminInboxRoute: AdminInboxRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminPerksRoute: AdminPerksRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminStepsRoute: AdminStepsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminVideosRoute: AdminVideosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutConciergeCareRoute: AboutConciergeCareRoute,
  AdminRoute: AdminRouteWithChildren,
  AffiliateBenefitsRoute: AffiliateBenefitsRoute,
  BecomeAnAffiliateRoute: BecomeAnAffiliateRoute,
  BlogRoute: BlogRouteWithChildren,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  DoNotSellRoute: DoNotSellRoute,
  FindADoctorRoute: FindADoctorRoute,
  LoginRoute: LoginRoute,
  MemberBenefitsRoute: MemberBenefitsRoute,
  MemberFaqRoute: MemberFaqRoute,
  MemberProgramsRoute: MemberProgramsRoute,
  NonDiscriminationRoute: NonDiscriminationRoute,
  OurDoctorsRoute: OurDoctorsRoute,
  OurMissionRoute: OurMissionRoute,
  OurTeamRoute: OurTeamRoute,
  PhysicianFaqRoute: PhysicianFaqRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SellYourPracticeRoute: SellYourPracticeRoute,
  SitemapRoute: SitemapRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SuccessStoriesRoute: SuccessStoriesRoute,
  TermsRoute: TermsRoute,
  TestimonialsRoute: TestimonialsRoute,
  TransitionRoute: TransitionRoute,
  VideoLibraryRoute: VideoLibraryRoute,
  WhatIsConciergeMedicineRoute: WhatIsConciergeMedicineRoute,
  WhyConciergeMedicineRoute: WhyConciergeMedicineRoute,
  DoctorsSlugRoute: DoctorsSlugRoute,
  ForDoctorsBlogRoute: ForDoctorsBlogRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
